Document: libads
Title: Debian libads Manual
Author: <insert document author here>
Abstract: This manual describes what libads is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libads/libads.sgml.gz

Format: postscript
Files: /usr/share/doc/libads/libads.ps.gz

Format: text
Files: /usr/share/doc/libads/libads.text.gz

Format: HTML
Index: /usr/share/doc/libads/html/index.html
Files: /usr/share/doc/libads/html/*.html
